sonar.projectKey=jhermesn_ci-cd-example-pipeline
sonar.organization=jhermesn

sonar.sources=.
sonar.exclusions=**/*_test.go

sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
